language: python

python:
    - "3.6"
install:
    - pip install -r requirements.txt
addons:
    code_climate:
        repo_token: d2c720a6af56c89c672b69b9d16962da52b1e0611c33f19e8a15b048457b2d62
script: 
    - nosetests --with-coverage
    - coverage report 
cache: pip

